dubbo:
  scan:
    base-packages: com.alibaba.cloud.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
      accesslog: true
    rest:
      name: rest
      port: 8080
      server: tomcat
      accesslog: true
  registry:
    #   The Spring Cloud Dubbo's registry extension
    #    address: spring-cloud://localhost
    #   The traditional Dubbo's registry
    address: nacos://10.199.198.220:8848
#feign:
#  hystrix:
#    enabled: true